services:
  - docker
before_install:
  - docker run --rm -i lukasmartinelli/hadolint hadolint --ignore DL4000 --ignore DL3008 - < Dockerfile
install:
  - docker build -t coredns .
  - docker run -d -p 127.0.0.1:53:53 --name coredns coredns
script:
  - docker ps | grep -q coredns 
