---
version: '3.1'
services:
  coredns:
    image: yorickps/coredns
    #build: .
    container_name: coredns 
    restart: on-failure
    expose:
      - '53'
      - '53/udp'
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - './config:/etc/coredns'
